### PR TITLE
Add timeout parameter to requests calls

### PR DESCRIPTION
**Pull request by fkrestan**
Requests library does not have any request timeout by default. This prevents
client hanging infinitely.

### CODE REVIEW

**Comment by fkrestan** [comment]
It looks like `coveralls` is missing an api token.

**Comment by jdelic** [comment]
> Requests library does not have any request timeout by default. This prevents client hanging infinitely.

That's a very good addition thank you.

> It looks like coveralls is missing an api token.

It actually doesn't, it's just that because it's a secret API key, travis.ci hides it from PR builds from different repos, so I would need to import this PR to the main repo to run the coverage tests. I'll have to find a different solution for that.

**Comment by findmyname666** [comment]
I would vote for 10-15s :)

**Comment by jdelic** [comment]
15s might be a bit low... publishing a larger snapshot can easily take a minute or more in my experience. So I'm wondering whether a low default like 15s might be surprising. An indefinitely hanging client is, of course, also surprising. Hmm. Opinions?

@findmyname666 why 10-15s? Did you choose that deliberately? What's your experience?

**Comment by findmyname666** [comment]
> 15s might be a bit low... publishing a larger snapshot can easily take a minute or more in my experience. So I'm wondering whether a low default like 15s might be surprising. An indefinitely hanging client is, of course, also surprising. Hmm. Opinions?
> 
> @findmyname666 why 10-15s? Did you choose that deliberately? What's your experience?

Hi there, I didn't detected the large processing time during publish state. It can also depend on network quality, etc. I have no issue to raise it to 60s or a bit more but keep in mind that it's the default option anybody can override it ...

**Comment by fkrestan** [comment]
I don't really see any problems with longer timeout since it can be overridden by new users while not breaking as much stuff for current library users.

So to move with this discussion forward; How long is long enough?

**Comment by jdelic** [comment]
I decided on `60s` for now in #37, which is this PR local to this repo so that tests can run on TravisCI. Thank you everyone!

**Comment by jdelic** [comment]
@fkrestan v0.2.0 is now on pypi. I will add you to the list of contributors if you don't mind.

**Comment by fkrestan** [comment]
> I will add you to the list of contributors if you don't mind.

I don't mind.

@jdelic, thanks a lot four your time.

**Pull request closed without merging**
