### PR TITLE
add and pass timeout parameter to fix #58

### LINKED ISSUE #58: Using a custom timeout to reach the aptly API
Hello,

Is it possible today to specify a custom timeout to reach the aptly API ?
I saw in the function `BaseAPIClient` than there is a timeout parameter.
But not in `Client` class, is-it normal ?

Thanks.

### PR DESCRIPTION
**Pull request by jdelic**

### CODE REVIEW

**Comment by smutel** [comment]
Could we merge this ?

**Comment by jdelic** [comment]
@smutel 
yes. Done.

**Comment by smutel** [comment]
Thanks. When do you think you will create a new tag ?

**Comment by jdelic** [comment]
@smutel 
sorry for this taking so long. v0.2.3 has been [uploaded to Pypi](https://pypi.org/project/aptly-api-client/).

**Pull request merged**
